---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
spec:
  ports:
  - name: jenkins-http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins-jnlp
  namespace: jenkins
spec:
  ports:
  - name: agent
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins
  type: ClusterIP
