apiVersion: v1
kind: Service
metadata:
  name: sonatype-nexus
  namespace: nexus
  labels:
    app: sonatype-nexus
spec:
  type: NodePort
  ports:
  - name: sonatype-nexus
    port: 8081
    targetPort: 8081
    nodePort: 8081
    protocol: TCP
  - name: docker-registry
    port: 8082
    targetPort: 8082
    nodePort: 8082
    protocol: TCP
  selector:
    app: sonatype-nexus
