apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sonatype-nexus
  name: sonatype-nexus
  namespace: nexus
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sonatype-nexus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sonatype-nexus
    spec:
      containers:
      - env:
        - name: INSTALL4J_ADD_VM_PARAMS
          value: ' -Xms2G -Xmx4G -XX:MaxDirectMemorySize=4G -XX:+UnlockExperimentalVMOptions
            -XX:+UseCGroupMemoryLimitForHeap '
        image: k8s.harbor.cn/k8s-component/sonatype/nexus:3-3.30.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: sonatype-nexus
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 500m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: cce-evs-nexus3
